### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

### ISSUE THREAD

**Issue by wxr521314** [huangmozhilv/u2net_torch#10]
Hi brother：
    Thank you for sharing, I am a little white in image processing. I hope to get your helpI    When I run " CUDA_VISIBLE_DEVICES=1 python train_model_no_adapters.py --trainMode 'independent' --out_tag '20190312' --tasks 'Task10_Colon" on my terminal.  The following problem arises
![image](https://user-images.githubusercontent.com/53425125/86477167-741def00-bd7a-11ea-991a-d0d2be37502b.png)

    Maybe my data path is not set correctly, where should I modify my path?
![image](https://user-images.githubusercontent.com/53425125/86477334-c9f29700-bd7a-11ea-85ed-72b5ac8df6b2.png)
Is it here?This problem occurred again after I modified it
![image](https://user-images.githubusercontent.com/53425125/86477414-f8707200-bd7a-11ea-9681-66a7e80407cc.png)
   I'm looking forward to receiving your reply as soon as possible
Best wish!

**Comment by Forest-Xie** [comment]
just change the path named preData_dir in file config.py from [''...''] to "..."
