### ISSUE TITLE
question about memory

### ISSUE THREAD

**Issue by Forest-Xie** [huangmozhilv/u2net_torch#12]
Hi, thanks for your work. I have fix some small question about your code, then I got right performance. But I have some question about your experiment and your code.
That is, I use torchsummary to see how much memory your model need to occupied, and I got 19136MB with input size(2, 1, 80, 192, 128), but my gpu has just 11GB  memory to use, and I can run the code. That's amazing! I checked your code,  but I can not find the mechanism to reduce memory so obviously.
Can you or somebody else can answer me? Thanks so much.

**Comment by huangmozhilv** [comment]
There might be something wrong with computation of the memory required by `torchsummary`. Anyway, pay attention to the true memory occupied on GPU when running the code.
