### ISSUE TITLE
How to train the self-data

### ISSUE THREAD

**Issue by yl255** [huangmozhilv/u2net_torch#2]
Hi,
Thank you for your great work!
but I want to know how to train my self data with your model.
For example, how to set the batch_size, and the patch_size and other parameters in the config.py.
and how to inference the test data.
Best,
Yaliang

**Comment by huangmozhilv** [comment]
Hi @yl255, you can easily find the implementation details in the 2nd paragraph of "Preprocessing" section of the [paper](https://arxiv.org/pdf/1909.06012.pdf). More details can be found in [paper of "nnU-Net"](https://arxiv.org/abs/1809.10486).
