### ISSUE TITLE
No module named 'batchgenerators'

### ISSUE THREAD

**Issue by GaaiWai** [huangmozhilv/u2net_torch#4]
Hi, your work is really admirable, but when I train it on google colab, an unexpected error occured. I have no idea, could you help me address this problem? Thanks
     14 from termcolor import colored
     15 
---> 16 import batchgenerators
     17 
     18 import ccToolkits.logger as logger

ModuleNotFoundError: No module named 'batchgenerators'

**Comment by huangmozhilv** [comment]
Hi @pjwhere, thank you. Most requirements are listed in `requirments.txt`. Besides, `batchgenerators` is a python package developed by researchers at the Division of Medical Image Computing at the German Cancer Research Center (DKFZ) to do data augmentation for images. Introduction and installation instructions are listed in [MIC-DKFZ/batchgenerators/](https://github.com/MIC-DKFZ/batchgenerators/).

**Comment by GaaiWai** [comment]
It suddenly occurred to me that you mentioned it in your paper. So sorry to bother you.Thanks for your reply.
