### ISSUE TITLE
Some problems about the implement of conv_unit?

### ISSUE THREAD

**Issue by mangoyuan** [huangmozhilv/u2net_torch#7]
In `conv_unit` module, when `config.module == 'separable_adapter'`, the `conv_unit` will return three tensor `out, share_map, para_map`.
https://github.com/huangmozhilv/u2net_torch/blob/81949372ad321e0f63026b58a1d81e0e1e0b6da9/u2net_torch_src/models/u2net3d.py#L141

And in the module `DownBlock`,  only when 'config.module == `parallel_adapter`', the module will run `out, share_map, para_map = self.op1(x)`. When `separable_adapter`, it will run `out = self.op1(x)` and the out now is the list of `(out, share_map, para_map)`. Next step the leakly ReLU activation `out = self.act1(out)` will raise error `TypeError: leaky_relu(): argument 'input' (position 1) must be Tensor, not tuple`
https://github.com/huangmozhilv/u2net_torch/blob/81949372ad321e0f63026b58a1d81e0e1e0b6da9/u2net_torch_src/models/u2net3d.py#L181

I'm not sure if it's just me, my pytorch version is 1.1.
In the end, thanks for your contirbutions and sharing!

**Comment by huangmozhilv** [comment]
There might be some typos when cleaning the code. Please try change `config.module == 'parallel_adapter'` to `config.module == 'parallel_adapter' or config.module == 'separable_adapter'` in `forward` of `DownBlock`.

**Comment by mangoyuan** [comment]
Before you reply, I change it in `DownBlock`, `Upsampling` and `u2net`. It works well. Thanks for your reply. I close this issue now.

**Comment by fornote** [comment]
hello, I have the same problem with you. As the author and you said, I  combine this two point. I try to change all  `config.module == 'parallel_adapter'` to `config.module == 'parallel_adapter' or config.module == 'separable_adapter'` in `forward` of `DownBlock`, `UnetUpsample`, `UpBlock` and `u2net3d`. But the problem is not resolved, and thank you for asking this question.

**Comment by huangmozhilv** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    What’s the error message? You can try the code I updated two days ago.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                huangcaojiujiu
                            
                    
                        
                            
                                    huangcaojiujiu@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 04/2/2020 22:58，fornote<notifications@github.com> wrote： 



hello, I have the same problem with you. As the author and you said, I  combine this two point. I try to change all  config.module == 'parallel_adapter' to config.module == 'parallel_adapter' or config.module == 'separable_adapter' in forward of DownBlock, UnetUpsample, UpBlock and u2net3d. But the problem is not resolved, and thank you for asking this question.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fornote** [comment]
> font{
>         line-height: 1.6;
>     }
>     ul,ol{
>         padding-left: 20px;
>         list-style-position: inside;
>     }
> 
> 
> 
>     What’s the error message? You can try the code I updated two days ago.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>                                 huangcaojiujiu
> 
> 
> 
> 
>                                     huangcaojiujiu@gmail.com
> 
> 
> 
> 
> 
> 
> 
> 
>         签名由
>         网易邮箱大师
>         定制
> 
> 
> 
> 
>     On 04/2/2020 22:58，fornote<notifications@github.com> wrote：
> 
> 
> 
> hello, I have the same problem with you. As the author and you said, I  combine this two point. I try to change all  config.module == 'parallel_adapter' to config.module == 'parallel_adapter' or config.module == 'separable_adapter' in forward of DownBlock, UnetUpsample, UpBlock and u2net3d. But the problem is not resolved, and thank you for asking this question.
> 
> —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much, I have just solved it using your old code. The argparse inputs of trainMode and module caused the error, and I just wrote this two parameters in code instead of entering with keyboard.
